### ISSUE TITLE
Audio embed support

### ISSUE THREAD

**Issue by siers** [kamalsacranie/anki-panky#11]
It looks like there isn't any? What would the syntax look like?

**Comment by kamalsacranie** [comment]
hey mate. Indeed there is no audio support currently. I've always been a bit too lazy to embed audio in my flashcards. I'll have to do a bit of research to see how it's handled internally but im super down to implement it. In terms of syntax, I think it would be pretty elegant if we use the same syntax as for images `![]()` but the type of document was inferred at transpile-time. E.g., `![](my-audo.mp3)` would be handles as audio and anything without an audio extension could be handled as an image. Let me know if you have any bring ideas for syntax. Always open to suggestions.

I'll aim to include audio support in the next release

**Comment by kamalsacranie** [comment]
This actually already works. Tried it today. Just reference an mp3 the same way you do an image file and it will embed an audio html tag like this:

```html
<audio src="your-audio.mp3" controls=""><a href="your-audio.mp3">Audio</a></audio>
```

Which in Anki renders as audio control. This isn't exactly the same as how Anki natively embeds audio but I'd actually more portable this way because it's just HTML. Give it a try and let me know how it goes please.

**Comment by siers** [comment]
Huh, nice! I'll try this out.
