### ISSUE TITLE
Feature: bidirectional synchronization support after editing in Anki

### ISSUE THREAD

**Issue by siers** [kamalsacranie/anki-panky#9]
Is there any? Would it be possible to implement? More of a talking point, but I suppose it could be useful, since editing on phones is possible.

**Comment by kamalsacranie** [comment]
Just to clarify. You want to be able to edit/add a card in Anki and then basically update the markdown source in "reverse"?

If that is the case, it probably is possible but definitely not trivial. We'd have to export the updated collection's html and then transpile from HTML → markdown. This isn't necessarily impossible but the quality of the generated markdown may not match the source. This is because the transpiration from HTML → markdown can sometimes be lossy (and, of course, it's generated automatically).

It's quite a nice idea but It's probably out of the scope of this project for now. I agree it would be super convenient to edit a mistake on your phone and update the markdown source. Likely, it would need to be a separate project altogether.

LMK if I understood the question correctly :)

**Comment by siers** [comment]
> Just to clarify. You want to be able to edit/add a card in Anki and then basically update the markdown source in "reverse"?

Correct!

> It's quite a nice idea but It's probably out of the scope of this project for now. I agree it would be super convenient to edit a mistake on your phone and update the markdown source. Likely, it would need to be a separate project altogether.

👍 

Thank you for the response!

**Comment by kamalsacranie** [comment]
When I get around to thinking more about this I'll reopen the issue if I see that there is a nice way to implement this! Thanks for the suggestion anyway.
